### ISSUE TITLE
Just a note for users

### ISSUE THREAD

**Issue by hylinkdigital** [terbolous/craftcms-docker#2]
Hey there, thanks for setting this up. It's simple and smooth.

The only bump I encountered was a cookievalidation code error from Yii before I could install craft3.

This is resolved by copying the SECURITY_KEY environment variable definition from the .env.example file into the .env file and populating it with a sha string.

If you'd like I can submit a pull request that fixes this in the setup shell script.

**Comment by terbolous** [comment]
That would be great :-)

lør. 7. okt. 2017 kl. 00:05 skrev Hylink Digital Solutions <
notifications@github.com>:

**Comment by hylinkdigital** [comment]
ok, will do.

**Comment by hylinkdigital** [comment]
@terbolous : Pull Request created.
